# Generated by Django 2.2 on 2020-03-27 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSuggestionsRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=50)),
                ('disease_info', models.TextField(null=True)),
                ('remarks', models.TextField(null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_disable', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_patient_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_suggestions_request',
            },
        ),
        migrations.CreateModel(
            name='PatientSuggestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_response', models.TextField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_disable', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_doctor_response', to=settings.AUTH_USER_MODEL)),
                ('suggestion_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.PatientSuggestionsRequest')),
            ],
            options={
                'db_table': 'patient_suggestions_response',
            },
        ),
    ]
