# Generated by Django 2.2 on 2020-03-27 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsuggestionresponse',
            name='suggestion_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_suggestions_history', to='patient.PatientSuggestionsRequest'),
        ),
    ]
