# Generated by Django 2.2 on 2020-06-07 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('last', models.IntegerField()),
            ],
            options={
                'db_table': 'prescription_range',
            },
        ),
        migrations.CreateModel(
            name='TreatmentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(null=True)),
                ('prescription_no', models.CharField(max_length=20)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_treatments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_treatments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'treatment_history',
            },
        ),
        migrations.CreateModel(
            name='TreatmentMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=50)),
                ('morning', models.BooleanField(default=False)),
                ('evening', models.BooleanField(default=False)),
                ('night', models.BooleanField(default=False)),
                ('total_tablets', models.IntegerField()),
                ('purchased_tablets', models.IntegerField(default=0)),
                ('remaining_tablets', models.IntegerField(default=0)),
                ('treatment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_medicine', to='medicine.TreatmentHistory')),
            ],
            options={
                'db_table': 'treatment_medicine',
            },
        ),
    ]
