# Generated by Django 2.2 on 2020-06-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentmedicine',
            name='medicine_for_days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
